import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

const DATA_URL = 'https://denes0216.github.io/GeoCarHelpDesk/us-plates-data.js';
const IMG_BASE = 'https://denes0216.github.io/GeoCarHelpDesk/data/us-plates/';
const GEOJSON_URL =
  'https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json';

const ROOT = process.cwd();
const OUT_IMG_DIR = join(ROOT, 'public/us-plates');
const OUT_DATA = join(ROOT, 'src/data/us-plates.ts');
const OUT_GEOJSON = join(ROOT, 'public/us-states.geo.json');

interface USPlateRaw {
  state: string;
  difficulty: 'easy' | 'somewhat' | 'harder';
  file: string;
  colors: string[];
  label: string;
}

async function main() {
  // 1. Fetch and parse plate data
  console.log('Fetching plate data…');
  const jsText = await fetch(DATA_URL).then((r) => r.text());
  const match = jsText.match(/window\.US_PLATES\s*=\s*(\[[\s\S]*\]);/);
  if (!match) throw new Error('Could not find window.US_PLATES in data file');
  // The data uses JS object literal syntax with comments — use Function eval to parse it

  const plates: USPlateRaw[] = new Function(`return ${match[1]}`)();
  console.log(
    `  Parsed ${plates.length} plates across ${new Set(plates.map((p) => p.state)).size} states`
  );

  // 2. Download images
  mkdirSync(OUT_IMG_DIR, { recursive: true });
  const files = [...new Set(plates.map((p) => p.file))];
  console.log(`Downloading ${files.length} plate images…`);
  for (const file of files) {
    const buf = await fetch(IMG_BASE + file).then((r) => r.arrayBuffer());
    writeFileSync(join(OUT_IMG_DIR, file), Buffer.from(buf));
    process.stdout.write('.');
  }
  console.log('\n  Images saved to public/us-plates/');

  // 3. Write TypeScript data file
  const ts = `// Generated by scripts/download-us-plates.ts — do not edit manually

export interface USPlate {
  state: string;
  difficulty: 'easy' | 'somewhat' | 'harder';
  file: string;
  colors: string[];
  label: string;
}

export const PLATES_IMAGE_BASE = '/us-plates/';

export const US_PLATES: USPlate[] = ${JSON.stringify(plates, null, 2)};
`;
  writeFileSync(OUT_DATA, ts);
  console.log('  TypeScript data written to src/data/us-plates.ts');

  // 4. Download GeoJSON
  console.log('Fetching US states GeoJSON…');
  const geojson = await fetch(GEOJSON_URL).then((r) => r.text());
  writeFileSync(OUT_GEOJSON, geojson);
  console.log('  GeoJSON saved to public/us-states.geo.json');

  console.log('\nDone!');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
